doctrine:
    dbal:
      default_connection: panel
      connections:
        panel:
          url: '%env(resolve:DATABASE_URL)%'
        aqg:
          url: '%env(resolve:DATABASE_CUSTOMER_URL)%'
    orm:
        default_entity_manager: panel
        entity_managers:
          panel:
            connection: panel
            mappings:
                App:
                    is_bundle: false
                    dir: '%kernel.project_dir%/src/Entity/panel'
                    prefix: 'App\Entity\panel'
                    alias: App
          aqg:
            connection: aqg
            mappings:
                aqg:
                    is_bundle: false
                    dir: '%kernel.project_dir%/src/Entity/aqg'
                    prefix: 'App\Entity\aqg'
                    alias: aqg
